### PR TITLE
Added Suggestion on Search bar

### PR DESCRIPTION
**Pull request by alchemist0404**

### CODE REVIEW

**Review by NunoMartins21 — CHANGES_REQUESTED** [review]
A few thing I noticed:

1. the profile pictures are weird. They shouldn't be stretched out; instead, they should fill the whole space with a centered position. You might wanna use `object-fit: cover;` for this.

image

2. the paddings are a bit off. This is something you probably need to ask Harisson though, but I think you should have the same padding for either the left and the right.

image

3. you're showing the suggestion menu even when there are no results for that query. We should hide the menu.

image

**Comment by alchemist0404** [comment]
@NunoMartins21 I think this way is better than hiding menu for the UX.
image

**Comment by alchemist0404** [comment]
@NunoMartins21 I have updated, please check

**Review by NunoMartins21 — APPROVED** [review]
Nice, that's what we wanted. Approved and ready to be merged.

**Pull request merged**
