### PR TITLE
Discord invite link fixed

### PR DESCRIPTION
**Pull request by Ashishgy**
Discord Link change, as previously it was showing alchemist has invited you to join.

Now It says Gateway has invited you to join

### CODE REVIEW

**Comment by otrsk** [comment]
(This isn’t for a discord bot, but for discord, right?) I think it pays off to put URLs and keys into separate constants even if they’re only used once because it’s quite likely they will be re-used or changed at some point and this provides for fewer errors later, and is a general ‘good practice’ that’s still very cheap to implement.

**Comment by NunoMartins21** [comment]
Can we implement that idea then @Ashishgy?

I'd say we can use our `utils/constants.ts` file for this purpose. Create a `SOCIALS` constant object on that file, with a field `DISCORD` with our Discord URL, and update our footer with the correct link by associating this new created constant.

**Comment by Ashishgy** [comment]
Sure I will do It

**Comment by otrsk** [comment]
@Ashishgy pls convert a PR to a draft in such a case (to mean that it's NOT ready to be reviewed and merged). I've done that here now.

**Comment by NunoMartins21** [comment]
Approved @Ashishgy. I just changed a bit on how you're exporting the `SOCIALS` constant (not as the default file export, but just as a regular export) and fixed a bug on the header (it was redirecting me to `http://localhost:3000/discord...`)

**Pull request merged**
