### PR TITLE
Fixed User/Admin Dashboard (Differentiate Gate View)

### PR DESCRIPTION
**Pull request by alchemist0404**

### CODE REVIEW

**Review by NunoMartins21 — CHANGES_REQUESTED** [review]
I don't know what was the idea here, but I'm assuming it's to differentiate between users and admins on the gate page (so admins that are viewing the gate as members don't see the admins buttons). But this is not working, if this is the idea at least.

Even though you're passing the correct search parameters, it doesn't do anything. I think you forgot to actually use the parameter to hide/show the buttons, no?

**Comment by alchemist0404** [comment]
https://www.loom.com/share/7c6797da672341fdb06375b02b2512c5
Please check this video. Ayyan found this issue and I have fixed.

**Comment by alchemist0404** [comment]
@NunoMartins21 Is there any something needs to be changed on this PR?

**Comment by alchemist0404** [comment]
@NunoMartins21 I have fixed the `search subdomain` issue, please check. and is there anything to be changed for this PR? This PR is not merged for long time.

**Pull request closed without merging**
